In [21]:
## machine learning

# with help of past data we will make patterns or decision
## supervised : target variable : fever or not
## inputs : temp , cold , cough , headache , patient name
## independent(x) and dependent(y) -> LABEL DATA
## DISCRETE -> CONSTANT VALUES -> TARGET VARIABLE -> CLASSIFICATION
## CONTINOUS -> decimal value -> 0.1,1,2,1.3 -> Regression -> Salary
## unsupervised -> similarity or grouping
## unlabel data -> similarity or grouping
## clustering -> kmeans , hierchial , dbscan , recommendation engine ,
## dimensional reduction(pca) -> eigen values
## reinforcement : self - learning -> gen ai or agentic ai -> rewards or penalty

In [22]:
## classification:
#logistic
#knn classifier
#svm classifier
#decision tree

## regressiom
## linear
## knn reg
## svm reg
## decision tree reg

## ensemble -> creating multiple models
## voting
## stacking
## bagging -> random forest
## boosting -> adaboost or xgboost -> serialization

In [23]:
## machine learning process
## goal : fever or no fever
## collecting data
## loading data
## data cleaning
##feature engineering
## 1. Feature selection
## 2. Feature transformation
## yes or no -> yes - 0 no - 1
## splitting data - train and test
## train data -> blackbox -> model
## model -> data -> predictions
## model evaluation -> best or not

In [24]:
## importing lib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv('/content/car_pricing_dataset.csv')
df.head(10)

,Car_Age,Mileage_km,Engine_CC,Horsepower,Fuel_Type,Transmission,Brand,Body_Type,Previous_Owners,Car_Price_INR
0,6,110878,3000,128,Petrol,Automatic,Audi,Hatchback,1,3541000
1,3,169899,2500,296,CNG,Manual,Ford,SUV,0,3461000
2,12,67623,800,63,Petrol,Manual,Tata,Hatchback,1,786000
3,14,80450,3000,75,CNG,Manual,Mercedes,Hatchback,0,2520000
4,10,98426,1200,83,Petrol,Automatic,Toyota,MUV,3,1039000
5,7,122845,3000,139,CNG,Automatic,Tata,Hatchback,2,2664000
6,12,158371,1000,61,Petrol,Automatic,Ford,Sedan,3,577000
7,4,48585,800,279,Electric,Automatic,Tata,Hatchback,1,2646000
8,6,114225,1000,187,Diesel,Automatic,Ford,Sedan,1,1928000
9,9,69044,2500,219,Petrol,Automatic,Ford,Sedan,3,2482000

In [26]:
df = pd.read_csv('/content/car_pricing_dataset.csv')
df.tail(10)

,Car_Age,Mileage_km,Engine_CC,Horsepower,Fuel_Type,Transmission,Brand,Body_Type,Previous_Owners,Car_Price_INR
190,11,38828,1500,185,Petrol,Manual,BMW,SUV,0,2989000
191,12,154783,1000,254,Petrol,Automatic,Toyota,Hatchback,3,1623000
192,2,8420,1500,232,Electric,Manual,Tata,Hatchback,2,2647000
193,14,101752,2500,200,CNG,Manual,Tata,Hatchback,2,1876000
194,6,136373,1000,279,CNG,Automatic,Kia,MUV,1,2389000
195,0,120294,1000,185,CNG,Automatic,Maruti,MUV,0,2272000
196,3,129019,1200,117,CNG,Automatic,Ford,Sedan,0,2272000
197,12,70726,1000,207,Petrol,Automatic,BMW,Sedan,1,2597000
198,3,146564,3000,279,Petrol,Automatic,Mercedes,SUV,2,4489000
199,13,120668,800,259,Diesel,Manual,Toyota,MUV,3,1510000

In [27]:
df.shape

(200, 10)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Car_Age          200 non-null    int64
 1   Mileage_km       200 non-null    int64
 2   Engine_CC        200 non-null    int64
 3   Horsepower       200 non-null    int64
 4   Fuel_Type        200 non-null    object
 5   Transmission     200 non-null    object
 6   Brand            200 non-null    object
 7   Body_Type        200 non-null    object
 8   Previous_Owners  200 non-null    int64
 9   Car_Price_INR    200 non-null    int64
dtypes: int64(6), object(4)
memory usage: 15.8+ KB

In [29]:
## checking null values
df.isnull().sum()

Car_Age            0
Mileage_km         0
Engine_CC          0
Horsepower         0
Fuel_Type          0
Transmission       0
Brand              0
Body_Type          0
Previous_Owners    0
Car_Price_INR      0
dtype: int64

In [30]:
## checking duplicate
df.duplicated().sum()

np.int64(0)

In [31]:
df.drop_duplicates(inplace=True)

In [32]:
## ml - sklearn
y= df['Car_Price_INR']
x = df.drop(labels="Car_Price_INR",axis=1)

In [33]:
x_num = x.select_dtypes(include="int64")
x_num.head()

   Car_Age  Mileage_km  Engine_CC  Horsepower  Previous_Owners
0        6      110878       3000         128                1
1        3      169899       2500         296                0
2       12       67623        800          63                1
3       14       80450       3000          75                0
4       10       98426       1200          83                3

In [34]:
x_char = x.select_dtypes(exclude="int64")
x_char.head()

  Fuel_Type Transmission     Brand  Body_Type
0    Petrol    Automatic      Audi  Hatchback
1       CNG       Manual      Ford        SUV
2    Petrol       Manual      Tata  Hatchback
3       CNG       Manual  Mercedes  Hatchback
4    Petrol    Automatic    Toyota        MUV

In [38]:
## char
## nominal -> one hot enocoder
## ordinal ->label encoder

In [39]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

In [48]:
# fit-learning transform - applying
## fit-transform - learning and applying
encoded_data = ohe.fit_transform(x_char)
x_encoded = pd.DataFrame(encoded_data,
                         columns=ohe.get_feature_names_out(x_char.columns),
                         index = x_char.index)
x_encoded.head()

,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Brand_Audi,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Body_Type_Hatchback,Body_Type_MUV,Body_Type_SUV,Body_Type_Sedan
0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [49]:
# num - scaling
## feature1 - 1 -10 , feature2 - 1-100000
## standard scalar : -3 to 3
## min max scaling : 0 to 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [50]:
x_scaling = pd.DataFrame(sc.fit_transform(x_num),
                       columns=x_num.columns,
                       index=x_num.index)
x_scaling.head()

    Car_Age  Mileage_km  Engine_CC  Horsepower  Previous_Owners
0 -0.336414    0.300066   1.703100   -0.833038        -0.312865
1 -1.032444    1.511971   1.011346    1.656296        -1.219719
2  1.055645   -0.588109  -1.340621   -1.796173        -0.312865
3  1.519664   -0.324727   1.703100   -1.618363        -1.219719
4  0.591625    0.044383  -0.787217   -1.499824         1.500844

In [51]:
data= pd.concat([x_scaling,x_encoded],axis=1)
data.head()

,Car_Age,Mileage_km,Engine_CC,Horsepower,Previous_Owners,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,...,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Body_Type_Hatchback,Body_Type_MUV,Body_Type_SUV,Body_Type_Sedan
0,-0.336414,0.300066,1.703100,-0.833038,-0.312865,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-1.032444,1.511971,1.011346,1.656296,-1.219719,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.055645,-0.588109,-1.340621,-1.796173,-0.312865,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,1.519664,-0.324727,1.703100,-1.618363,-1.219719,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.591625,0.044383,-0.787217,-1.499824,1.500844,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,y,test_size=0.2,random_state=56)

In [53]:
print(df.shape)
print(x_train.shape)
print(x_test.shape)

(200, 10)
(160, 25)
(40, 25)

In [54]:
y_train

125    3128000
117    1369000
41      887000
53     3442000
84     3459000
        ...
122    1665000
162     763000
192    2647000
143    2183000
85     2899000
Name: Car_Price_INR, Length: 160, dtype: int64

In [55]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [56]:
ypred = lr.predict(x_test)
ypred

array([3606604.66417829, 2524543.58341375, 1488364.19371389,
       2861660.68944576, 1778715.04914997, 2571254.71862088,
       1912299.19116333, 1172301.05883429, 2393803.82501277,
       2432436.86324842, 3186759.09662717, 1915645.34104413,
       3471902.05769324, 2819124.34150534, 2361317.47618907,
       2740596.22109844, 3471675.7666555 , 2679361.9942524 ,
       2009588.63757663, 2926020.89854667, 2436548.91036732,
       1649649.55883709, 1251592.47206892, 3659955.03418679,
       3035494.50036783, 1886433.79471877, 1720878.17503979,
       1619655.53301334, 1113435.95934925, 2508744.85981865,
       2031604.385108  ,  597222.04118782, 1623094.03370385,
       4145115.84568268, 3382589.11170882, 3567898.3137708 ,
       2907139.24903751, 2606987.78013322, 2191444.62451935,
       3133864.4851497 ])